files:
  - source: locales/en-US/browser/browser/zen-general.ftl
    translation: locales/browser/browser/zen-general.ftl
  - source: locales/en-US/browser/browser/zen-split-view.ftl
    translation: locales/browser/browser/zen-split-view.ftl
  - source: locales/en-US/browser/browser/zen-vertical-tabs.ftl
    translation: locales/browser/browser/zen-vertical-tabs.ftl
  - source: locales/en-US/browser/browser/zen-welcome.ftl
    translation: locales/browser/browser/zen-welcome.ftl
  - source: locales/en-US/browser/browser/zen-workspaces.ftl
    translation: locales/browser/browser/zen-workspaces.ftl
  - source: locales/en-US/browser/browser/preferences/zen-preferences.ftl
    translation: locales/browser/browser/preferences/zen-preferences.ftl
  - source: locales/en-US/browser/browser/zen-folders.ftl
    translation: locales/browser/browser/zen-folders.ftl
