name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report!

        ## Important
        - Please search existing issues to avoid creating duplicates.
        - For enhancement requests, please use GitHub Discussions.
        - Please fill out the template below to the best of your ability.
        - Please describe the issue as much as possible and provide steps to reproduce it along with visual aids if possible.
  - type: checkboxes
    id: captchas
    attributes:
      label: Captchas
      description: Just making sure you did actually read the instructions.
      options:
        - label: I have read the instructions.
        - label: I have searched existing issues and avoided creating duplicates.
        - label: I am not filing an enhancement request.
        - label: I have checked that this issue cannot be reproduced on Mozilla Firefox.
        - label: I have checked that this issue cannot be reproduced once I removed all my Mods and Custom CSS.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running? Please do not use "latest" or "newest" as version numbers. Go to `Help -> About Zen` to find the version number.
      placeholder: 1.0.0b
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you seeing the problem on?
      multiple: true
      options:
        - Linux (AppImage)
        - Linux (Flatpak)
        - Linux (Tarball)
        - macOS - aarch64
        - macOS - Intel
        - Windows - x64
        - Windows - aarch64
        - Other
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: What component is this issue related to?
      options:
        - Other
        - Compact Mode
        - Workspaces
        - Mods / Themes
        - Glance
        - URL Bar
        - Tabs
        - Settings
        - Privacy
        - Performance
        - Media Controler
        - Tab unloading
        - Tab Folders
        - Keyboard Shortcuts
        - Security
        - Extensions
        - Customizable UI / Toolbars
        - Localization
        - Bookmarks
        - Sync
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output if applicable
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
