name: Code Linter

on:
  push:
    branches:
      - dev
  workflow_call:
  pull_request:
    branches:
      - dev

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[no-lint]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Setup autopep8
        run: sudo apt install python3-autopep8

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
